version: '3'

services:

  firstlogservicecontainer:
    image: danielsperezb/logservicedate
    container_name: firstlogservicecontainer
    ports:
      - "35001:6000"
    environment:
      - PORT=6000
    networks:
      - arep_network

  secondlogservicecontainer:
    image: danielsperezb/logservicedate
    container_name: secondlogservicecontainer
    ports:
      - "35002:6000"
    environment:
      - PORT=6000
    networks:
      - arep_network

  thirdlogservicecontainer:
    image: danielsperezb/logservicedate
    container_name: thirdlogservicecontainer
    ports:
      - "35003:6000"
    environment:
      - PORT=6000
    networks:
      - arep_network

  db:
    image: danielsperezb/mongodb
    container_name: db
    volumes:
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    ports:
      - 27017:27017
    command: mongod
    networks:
      - arep_network

  web:
    image: danielsperezb/roundrobin
    container_name: roundrobincontainer
    ports:
      - "35000:6000"
    environment:
      - PORT=6000
    networks:
      - arep_network

networks:
  arep_network:
    driver: bridge

volumes:
  mongodb:
  mongodb_config:
